apiVersion: v1
kind: Pod
metadata:
  name: pyquote-pod
spec:
  containers:
    - name: pyquote-db
      image: docker.io/library/postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "quoteuser"
        - name: POSTGRES_PASSWORD
          value: "quotepass"
        - name: POSTGRES_DB
          value: "quotes"
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: init-script

    - name: pyquote-app
      image: pyquote:latest
      ports:
        - containerPort: 5000
      env:
        - name: DB_HOST
          value: "localhost"
      command: ["python", "app.py"]

  volumes:
  - name: init-script
    hostPath:
      path: ./init.sql
      type: File
